package br.com.weg.workshop.post.service;
import br.com.weg.workshop.audit.service.AuditService;
import br.com.weg.workshop.post.domain.*; import br.com.weg.workshop.post.dto.*; import br.com.weg.workshop.post.repository.*; import br.com.weg.workshop.preference.domain.Category; import br.com.weg.workshop.preference.repository.CategoryRepository; import br.com.weg.workshop.shared.error.*; import br.com.weg.workshop.user.domain.UserEntity; import br.com.weg.workshop.user.repository.UserRepository; import br.com.weg.workshop.workshop.domain.Workshop; import br.com.weg.workshop.workshop.repository.WorkshopRepository; import java.time.Instant; import java.util.*; import org.springframework.data.domain.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PostService { private final PostRepository posts; private final PostLikeRepository likes; private final PostCommentRepository comments; private final UserRepository users; private final WorkshopRepository workshops; private final CategoryRepository categories; private final AuditService audit; public PostService(PostRepository p,PostLikeRepository l,PostCommentRepository c,UserRepository u,WorkshopRepository w,CategoryRepository ca,AuditService audit){posts=p;likes=l;comments=c;users=u;workshops=w;categories=ca;this.audit=audit;}
 @Transactional public PostResponse create(UUID userId,PostRequest r){UserEntity u=user(userId);Post p=Post.create(r.title(),r.content(),r.image(),workshop(r.workshopId()),category(r.categoryId()),r.highlight(),u);posts.save(p);audit.record(userId,"CREATE","POST",p.getId(),null,"DRAFT");return response(p,userId);}
 @Transactional public PostResponse update(UUID userId,boolean admin,UUID id,PostRequest r){Post p=managed(userId,admin,id); if(p.getStatus()==PostStatus.PUBLISHED||p.getStatus()==PostStatus.ARCHIVED)throw new ConflictException("Published or archived posts cannot be edited.");String before=response(p,userId).toString();p.update(r.title(),r.content(),r.image(),workshop(r.workshopId()),category(r.categoryId()),r.highlight());audit.record(userId,"UPDATE","POST",id,before,response(p,userId).toString());return response(p,userId);}
 @Transactional public PostResponse schedule(UUID userId,boolean admin,UUID id,SchedulePostRequest r){Post p=managed(userId,admin,id);if(p.getStatus()!=PostStatus.DRAFT)throw new ConflictException("Only drafts can be scheduled.");p.schedule(r.scheduledAt());audit.record(userId,"SCHEDULE","POST",id,"DRAFT","SCHEDULED");return response(p,userId);}
 @Transactional public PostResponse publish(UUID userId,boolean admin,UUID id){Post p=managed(userId,admin,id);if(p.getStatus()!=PostStatus.DRAFT&&p.getStatus()!=PostStatus.SCHEDULED)throw new ConflictException("Post cannot be published.");String before=p.getStatus().name();p.publish();audit.record(userId,"PUBLISH","POST",id,before,"PUBLISHED");return response(p,userId);}
 @Transactional public PostResponse archive(UUID userId,boolean admin,UUID id){Post p=managed(userId,admin,id);if(p.getStatus()!=PostStatus.PUBLISHED)throw new ConflictException("Only published posts can be archived.");p.archive();audit.record(userId,"ARCHIVE","POST",id,"PUBLISHED","ARCHIVED");return response(p,userId);}
 @Scheduled(fixedDelayString="${app.posts.publication-interval-ms:60000}") @Transactional public void publishScheduled(){posts.findByStatusAndScheduledAtLessThanEqual(PostStatus.SCHEDULED,Instant.now()).forEach(p->{p.publish();audit.record(null,"PUBLISH","POST",p.getId(),"SCHEDULED","PUBLISHED");});}
 @Transactional(readOnly=true) public Page<PostResponse> feed(UUID userId,Instant updatedAfter,Pageable page){return posts.findFeed(userId,updatedAfter,page).map(p->response(p,userId));}
 @Transactional public void like(UUID userId,UUID id){Post p=published(id); if(!likes.existsByPostIdAndUserId(id,userId))likes.save(new PostLike(p,user(userId)));} @Transactional public void unlike(UUID userId,UUID id){published(id);likes.deleteByPostIdAndUserId(id,userId);}
 @Transactional public PostCommentResponse comment(UUID userId,UUID id,CreateCommentRequest r){return PostCommentResponse.from(comments.save(PostComment.create(published(id),user(userId),r.content())));}
 @Transactional(readOnly=true) public Page<PostCommentResponse> comments(UUID userId,UUID id,Pageable page){published(id);return comments.findByPostId(id,page).map(PostCommentResponse::from);}
 private PostResponse response(Post p,UUID userId){return PostResponse.from(p,likes.countByPostId(p.getId()),likes.existsByPostIdAndUserId(p.getId(),userId));} private Post published(UUID id){Post p=posts.findById(id).orElseThrow(()->new ResourceNotFoundException("Post not found."));if(p.getStatus()!=PostStatus.PUBLISHED)throw new ResourceNotFoundException("Post not found.");return p;} private Post managed(UUID u,boolean admin,UUID id){Post p=posts.findById(id).orElseThrow(()->new ResourceNotFoundException("Post not found."));if(!admin&&!p.getCreatedBy().getId().equals(u))throw new ResourceNotFoundException("Post not found.");return p;} private UserEntity user(UUID id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found."));} private Workshop workshop(UUID id){return id==null?null:workshops.findById(id).orElseThrow(()->new ResourceNotFoundException("Workshop not found."));} private Category category(UUID id){return id==null?null:categories.findById(id).orElseThrow(()->new ResourceNotFoundException("Category not found."));} }
